import { Col } from "react-bootstrap"

const FakeProfile = () => {
    return (
        <Col xs={12} md={7} lg={8} className="border border-1 border-black rounded rounded-2 bg-white">
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit.Illo soluta possimus voluptas deserunt! Et nesciunt laboriosam delectus cumque deleniti accusantium labore debitis rerum ? Voluptatum facilis possimus nobis blanditiis accusantium distinctio!</p>
        </Col>
    )
}

export default FakeProfile